### ISSUE TITLE
Ask native

### ISSUE THREAD

**Issue by szogun1910** [ESK0/eStickers#3]
Hey, after uploading your version I have two bugs

estickers.smx (eStickers): Native "eItems_GetPatchDisplayNameByPatchNum" was not found
eitems.smx (eItems): unexpected error 23 in AskPluginLoad callback

**Comment by ESK0** [comment]
> estickers.smx (eStickers): Native "eItems_GetPatchDisplayNameByPatchNum" was not found

This error is becouse eItems is not loaded properly.


> eitems.smx (eItems): unexpected error 23 in AskPluginLoad callback

Whats your eItems version + SM/MM version and whats your OS

**Comment by szogun1910** [comment]
`Whats your eItems version + SM/MM version and whats your OS`
Eitems  VERSION "0.19.1"
SourceMod Version: 1.10.0.6522
Metamod:Source version 1.10.7-dev
Os - Linux

**Comment by ESK0** [comment]
> `Whats your eItems version + SM/MM version and whats your OS` Eitems VERSION "0.19.1" SourceMod Version: 1.10.0.6522 Metamod:Source version 1.10.7-dev Os - Linux

Weird.. I am running SM: 1.10.0.6502 and MM: 1.11.0-dev+1144 and everything works just fine. 

Try SM 1.11 or older

**Comment by ESK0** [comment]
@szogun1910 Please check plugin folder if you have 2 eItems plugins. One has capital letter i and the other does not.  Please remove eItems and leave only the eitems.

This is more likely your issue.
