### ISSUE TITLE
PGL Players Stickers

### ISSUE THREAD

**Issue by metzz1** [ESK0/eStickers#4]
Nice work with eStickers and eItems!

How can I get the PGL Players Stickers on the menu?

They were released yesterday on the 9th of November.

**Comment by ESK0** [comment]
Hello,

working on a eItems data parser... after releasing open source version, an error occurred that caused the github data not to be updated automatically 

Edit: https://github.com/ESK0/eItems/commit/ba7266560b507ebb5af652faef135a0dcd4983c4
