### ISSUE TITLE
Unable to load plugin

### ISSUE THREAD

**Issue by aNXTYs** [ESK0/eStickers#8]
Hey there!
I tried to install the plugin but got this line printed from our cs server console.

[SM] Unable to load plugin "estickers.smx": Native "eItems_GetWeaponNumByDefIndex" was not found

It won't show up in the plugin list either (eitmes aswell, but got no error message so i guess its properly installed.)
I removed all the other eItems files aswell.

let me know if you can help me

- aNXiETY

**Comment by ESK0** [comment]
Hi,

first please provide me with SM,MM and eItems version.

**Comment by aNXTYs** [comment]
Thanks for the quick answer!

SM - SourceMod 1.10.0.6509
MM - Metamod:Source version 1.11.0-dev+1144
eItems - the one that is linked for requirements below the eStickers plugin

could the problem come from the rest in pawn plugin? I didn't change that one since the old sticker plugin used that aswell.

**Comment by ESK0** [comment]
Look into error log for further informations... `eItems_GetWeaponNumByDefIndex` means that eItems plugin is not loaded properly.  You can also use `sm plugins list` server console command to check if eItem is running.

**Comment by aNXTYs** [comment]
The issue is solved. I replaced the RestInPawn plugin with the linked version below eItems and it works now.

Thanks for your assistance ESK0, appreciate it!
